### ISSUE TITLE
Add smaller scale borders

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/vtex-tachyons#2]
The default `bw1` is too thick for finely detailed UI

**Comment by rodrigomuniz** [comment]
Mas `ba` `bt` `br` `bb` `bl` já aplica o `border: 1px solid` mínimo. 
Você só precisa adicionar o `bw1` `bw2`... se quiser começar a trabalhar com a escala. 

O problema maior que enfrentei, com bordas na store do render, foi não ter como mudar a espessura só de um dos lados do box model. Tipo, precisava de algo como `ba bb-w1`.

**Comment by dfosco** [comment]
Verdade! Abri essa issue quando estava começando a usar tachyons, hehe.

Sim, acho que vale criar classes específicas para bordas — tive que fazer uma customizada hoje mesmo.
