### ISSUE TITLE
Add fill module for coloring SVGs

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/vtex-tachyons#7]
I miss this all the time! Want to match SVG icon colors to fonts — don't have tachyons classes that set `fill` property 😢 

Anyone against it? @alenamiklos8 @zehfernandes @bernardolemgruber

**Comment by zehfernandes** [comment]
Done. 😎 

https://github.com/vtex-apps/vtex-tachyons/blob/master/src/_skins.css#L127
